tag-name = "{{crate_name}}-{{version}}"
pre-release-commit-message = ":bookmark: Bump {{crate_name}} version to {{version}}"
pre-release-hook = ["bash", "-lc", "cd $(git rev-parse --show-toplevel) && ./scripts/strip-readme-patch.sh {{version}}"]
