[alias]
xtask = "run --package xtask --"

[target."wasm32-wasi"]
runner = ["wasmtime", "--dir", "/"]
[target."wasm32-wasip1"]
runner = ["wasmtime", "--dir", "/"]
[target."wasm32-wasip2"]
runner = ["wasmtime", "--dir", "/"]
[target.wasm32-unknown-emscripten]
runner = "node"
[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"
rustflags = '--cfg getrandom_backend="wasm_js"'
